### ISSUE TITLE
Startup Script missing xfce

### ISSUE THREAD

**Issue by sonkatech** [jeremy-breidenbach/MyDearFreya#3]
Hey Jeremy,

Thanks for the making the code! Seems easier than MyDearWatson.

I'm having an issues finishing off the last command. I've followed the script word for word and the last part [sudo sh freya.sh continue] doesn't seem to work. I've had this same issue with MyDearWatson.

Do you have any solution?

Best
![screenshot 2016-04-26 at 10 07 56 am](https://cloud.githubusercontent.com/assets/17050877/14820945/c9c972de-0b96-11e6-9c2c-817306b2163a.png)

**Comment by jeremy-breidenbach** [comment]
Hi @sonkatech, FYI that I've since switched to using [GalliumOS](https://galliumos.org/) and haven't used crouton/MyDearFreya in a long time. I highly recommend GalliumOS for linux on your chromebook. 

I'm guessing you tried the MyDearWatson script first and then tried MyDearFreya. The MyDearWatson script creates a chroot called xfce and renames the "startxfce4" script (the one that starts the chroot) to "startelementary." That "startelementary" script was probably in your /usr/local/bin folder when you tried MyDearFreya and it's looking for the wrong chroot (looking for chroot named "xfce" instead of "freya"). I would try deleting the existing script from usr/local/bin (`cd /usr/local/bin`, then `sudo rm startelementary`), then cd to your downloads directory and do `sudo sh freya.sh continue` to install the correct "startelementary" script. If that doesn't work you could try powerwashing your chromebook again and starting fresh with MyDearFreya.

**Comment by sonkatech** [comment]
Thanks for the tip. Powerwashing did fix it. I'd appreciate it if you were to add that in the instructions for noobs like me.

Take care.
