### ISSUE TITLE
xinit: not found

### ISSUE THREAD

**Issue by gogobody** [jeremy-breidenbach/MyDearFreya#4]
`freya.sh:
130: C: not found
Picking up where we left off
All done, entering Elementary OS Freya
exec: 2: xinit: not found
`
After install , errors like this and I cant get into elementary,plz help

**Comment by jeremy-breidenbach** [comment]
Sorry, this project is no longer maintained as I haven't used Crouton in a long time. Did you have a previous install attempt of elementary? If yes it could have conflicted with this install. You could try power washing your Chromebook and starting fresh. I recommend Gallium OS instead of Crouton for your Chromebook, it is a much better experience.
